data:
  dataset: Shapes3D
  path: data/demo/Matterport3D_processed
  watertight_path: data/watertight
  classes: ['']
  input_type: pointcloud_crop
  train_split: train
  val_split: val
  test_split: test
  dim: 3
  points_file: null
  points_iou_file: null
  multi_files: null
  points_subsample: 1024
  points_unpackbits: true
  model_file: model.off
  watertight_file: model_watertight.off
  img_folder: img
  img_size: 224 
  img_with_camera: false
  img_augment: false
  n_views: 24
  pointcloud_file: pointcloud.npz
  pointcloud_chamfer_file: pointcloud
  pointcloud_n: 200000
  pointcloud_target_n: 1024
  pointcloud_noise: 0.0
  voxels_file: null
  padding: 0.1
  unit_size: 0.02 # define the size of a voxel, in meter
  query_vol_size: 90 # query crop in voxel
model:
  local_coord: True
  decoder: simple_local_crop
  encoder: pointnet_crop_local_pool
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
  encoder_kwargs:
    hidden_dim: 32
    plane_type: ['grid']
    unet3d: True
    unet3d_kwargs:
      num_levels: 4 # define the receptive field, 3 -> 32, 4 -> 64
      f_maps: 32
      in_channels: 32
      out_channels: 32
  multi_gpu: false
  c_dim: 32
training:
  out_dir: out/pointcloud_crop_training
  batch_size: 2
  print_every: 100
  visualize_every: 10000
  checkpoint_every: 1000
  validate_every: 1000000000 # TODO: validation for crop training
  backup_every: 10000
  eval_sample: false
  model_selection_metric: iou # iou or loss
  model_selection_mode: maximize # maximize or minimize
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  remove_wall: false
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/models/pointcloud_crop/room_grid64.pt
generation:
  sliding_window: True
  batch_size: 100000
  refinement_step: 0
  vis_n_outputs: 2
  generation_dir: generation
  use_sampling: false
  resolution_0: 128
  upsampling_steps: 0
  simplify_nfaces: null
  copy_input: true
  latent_number: 4
  latent_H: 8
  latent_W: 8
  latent_ny: 2
  latent_nx: 2
  latent_repeat: true
